export const default_piano_keyboard_layout = {
    "a": "A3",
    "w": "A#3",
    "s": "B3",
    "d": "C4",
    "r": "C#4",
    "f": "D4",
    "t": "D#4",
    "g": "E4",
    "h": "F4",
    "u": "F#4",
    "j": "G4",
    "i": "G#4",
    "k": "A4",
    "o": "A#4",
    "l": "B4",
    ";": "C5",
    "[": "C#5",
    "\'": "D5"
}